#!/bin/sh

set -eu

# Check for required packages/commands being installed
if [ "${1:-}" = "excessive" ]; then
  if [ ! -x "$(command -v supervisorctl 2>&1)" ]; then
    printf 'supervisorctl required but not found\n'
    exit 1
  fi
fi

# First we check startup services worked
# Or we would, except EXITED looks the same success or failure so there is no point
# In this case it's safe, because ssh won't come up unless these two succeeded
#for exited in sshdir sshkeys; do
#	if [ "$(supervisorctl status ${exited} | awk '{print $2}')" != "EXITED" ]; then
#		supervisorctl status
#		exit 1
#	fi
#done

# Next we check runtime services think they are running
for running in X11 novnc x11vnc xfce; do
  if [ "$(supervisorctl status ${running} | awk '{print $2}')" != "RUNNING" ]; then
    printf 'Something is wrong with service %s\n' "${running}"
    supervisorctl status
    exit 1
  fi
done

# Then we check the expected listening ports are actually listening
for port in 8080; do
  if ! ss -nlt | grep -q "0.0.0.0:${port}"; then
    printf 'Nothing is listening on port %s\n' "${port}"
    ss -nltp
    exit 1
  fi
done

printf "Everything looks good.\n"
true
