#!/bin/bash
#WARNING WARNING WARNING
#this rc file is meant for use on Nu only, please modify to meet your needs

export EMERGE_DEFAULT_OPTS="$(portageq envvar EMERGE_DEFAULT_OPTS) --jobs=32 --load-average=32 --backtrack=99"
export MAKEOPTS="-j32 -l32"
#export MAKEOPTS="-j1"
export INPUT_DEVICES="$(portageq envvar INPUT_DEVICES) synaptics"
export clst_myfeatures="$(portageq envvar FEATURES) parallel-install -ebuild-locks -preserve-libs -clean-logs -news splitdebug cgroup"
export FEATURES="$(portageq envvar FEATURES) parallel-install -ebuild-locks -preserve-libs -clean-logs -news splitdebug cgroup"
#export clst_myfeatures="$(portageq envvar FEATURES) parallel-install -ebuild-locks -preserve-libs -clean-logs -news splitdebug cgroup test test-fail-continue"
#export FEATURES="$(portageq envvar FEATURES) parallel-install -ebuild-locks -preserve-libs -clean-logs -news splitdebug cgroup test test-fail-continue"
export ACCEPT_LICENSE="Intel-SDP NVIDIA-CUDA"
export PORTAGE_NICENESS="15"
#c 0-3 n 0-7 lower number is higher priority
export PORTAGE_IO_NICENESS="ionice -c 3 -p \${PID}"
export PORT_LOGDIR="/var/log/portage"
export PORTAGE_COMPRESS=""
export CONFIG_CHECK_FATAL=0
export LANG="en_US.UTF-8"
export TERM="linux"
export INSTALL_MASK=""

export LC_ALL="C"

#kensington's tinderbox script settings
export TINDERBOX_DIR=/var/log/portage/tinderbox
export DEPCHECK_BIN=/etc/portage/depcheck

#this toggles on and off various debug shells to fix issues during catalyst builds
#export debugshell=true
