#!/bin/sh
catalyst -f stage1.spec || exit
catalyst -f stage2.spec || exit
catalyst -f stage3.spec || exit
catalyst -f stage4.spec || exit
catalyst -f livecd-stage1_template.spec || exit
catalyst -f livecd-stage2_template.spec || exit
