#!/bin/sh
catalyst -a -f stage1.spec || exit
catalyst -a -f stage2.spec || exit
catalyst -a -f stage3.spec || exit
catalyst -a -f stage4.spec || exit
catalyst -a -f livecd-stage1_template.spec || exit
catalyst -a -f livecd-stage2_template.spec || exit
