<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <title>Pentoo</title>
    <link rel="stylesheet" type="text/css" href="/media/default.css" media="screen">
  </head>
  <body style="text-align:center; ">
         <!-- default margin = default layout -->
         <div class="container" style="margin-left:auto; margin-right:auto;">
                <div class="header">
                        <a href="/"><span> </span></a>
                </div>
                <div class="nav">
                        <div>
                        <a href="/about" target=""><span> ABOUT</span><p>&nbsp;</p></a>
                        </div><div>
                        <a href="/docs" target=""><span> DOCS</span><p>&nbsp;</p></a>
                        </div><div>
                        <a href="/download" target=""><span> DOWNLOAD</span><p>&nbsp;</p></a>
                        </div><div>
                        <a href="http://forums.pentoo.ch/" target=" blank"><span> FORUMS</span><p>&nbsp;</p></a>
                        </div><div>
                        <a href="http://pentoo.blogspot.com/" target=" blank"><span> BLOG</span><p>&nbsp;</p></a>
                        </div><div>
                        <a href="http://trac.pentoo.ch/" target=" blank"><span> DEV</span><p>&nbsp;</p></a>
                        </div>
                        <div class="clearer"><span></span></div>
                </div>
                <div class="main">
                        <div class="content">
