#!/bin/sh

set -e

#disable things from grsec for building that we normally want enabled
sysctl -w kernel.grsecurity.chroot_deny_mknod=0 || echo "already disabled"
sysctl -w kernel.grsecurity.chroot_caps=0 || echo "already disabled"

#start a new screen session for the builds
screen -d -m -S catalyst -t catalyst bash

#attach to screen and auto-detach or it refuses to accept commands
#recurse screen inside screen or it won't run
screen -d -m screen -r catalyst
sleep 1
screen -d catalyst

#now run what we want

#take the snapshot
screen -S catalyst -p 0 -X stuff './snap.sh'$(printf \\r)

#kick off amd64 build
screen -S catalyst -p 0 -X stuff './run_catalyst.sh amd64'$(printf \\r)

#to keep io down we stagger the builds just a bit
screen -S catalyst -p 1 -X screen bash
screen -S catalyst -p 1 -X stuff 'sleep 20m'$(printf \\r)
screen -S catalyst -p 1 -X stuff './make_modules.sh'$(printf \\r)

screen -S catalyst -p 1 -X stuff './run_catalyst.sh i686'$(printf \\r)

screen -xr catalyst
