#!/bin/sh

#disable things from grsec for building that we normally want enabled
sysctl -w kernel.grsecurity.chroot_deny_mknod=0
sysctl -w kernel.grsecurity.chroot_caps=0

catalyst -f stage1.spec || exit
catalyst -f stage2.spec || exit
catalyst -f stage3.spec || exit
catalyst -f stage4.spec || exit

catalyst -f livecd-stage1.spec
if [ $? -ne 0 ]; then
	catalyst -f livecd-stage1.spec || exit
fi

catalyst -f livecd-stage2.spec || exit

mkdir /catalyst/release/Pentoo_i686
chmod 777 /catalyst/release/Pentoo_i686
su zero -c "gpg --sign --clearsign --yes --digest-algo SHA512 --default-key DD11F94A --homedir /home/zero/.gnupg `awk '/livecd\/iso:/ {print $2}' livecd-stage2.spec`.DIGESTS"

volid="$(grep ^livecd/volid livecd-stage2.spec | cut -d' ' -f2-)"
mktorrent -a http://tracker.cryptohaze.com/announce -n "${volid}" -o /catalyst/release/"${volid}".torrent /catalyst/release/Pentoo_i686

#tribe releases
catalyst -f livecd-stage1_tribe.spec || exit
catalyst -f livecd-stage2_tribe.spec || exit
