#!/bin/sh
#
# $Id: gprs-disconnect-chat,v 1.3.2.2 2006/02/14 20:20:17 mcfrisk Exp $
#
# File:
# gprs-disconnect-chat
#
# send break
exec /usr/sbin/chat -V -s -S	\
ABORT		"BUSY"		\
ABORT		"ERROR"		\
ABORT		"NO DIALTONE"	\
SAY		"\nSending break to the modem\n"	\
""		"\K"		\
""		"\K"		\
""		"\K"		\
""		"\d\d+++\d\dATH"	\
SAY		"\nPDP context detached\n"
