                        </div>
                        <div class="clearer"><span></span></div>
                </div>
                <div class="footer">
                        <div class="bottom">
                                <span class="left">&copy; 2010 <a href="/">Pentoo.ch</a>. </span>
                                <span class="right">Website template by <a href="http://arcsin.se/">Arcsin</a>, Graphic design by <a href="http://mellyart.com/">Melissa Holmes</a></span>
                                <div class="clearer"><span></span></div>
                        </div>
                </div>
         </div>
  </body>
</html>
